[package]
name = "glab"
version = "0.1.0"
authors = ["Akiacode <catry.me@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.4.0"
glab-api = { path = "../glab-api" }
clap = "2.33.3"
